### PR TITLE
Encode each path using www form

### LINKED ISSUE #33: Auth fails when glob pattern is used
Using the example on the page...
```elixir
AWSAuth.sign_url("AKIAIOSFODNN7EXAMPLE", "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
  "GET",
  "https://examplebucket.s3.amazonaws.com/*",
  "us-east-1",
  "s3",
  Map.new,
  ~N[2013-05-24 00:00:00])
```

This fails. The exact one I tested was using AWS elasticsearch service but I'm sure it's the same here

### PR DESCRIPTION
**Pull request by matrinox**
Fixes #33

URI.encode_www_form escapes special characters, which is what AWS does

### CODE REVIEW

**Comment by matrinox** [comment]
@radar PR is up. The solution come from reading [this article](http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html). Specifically this sentence in point 2:

> Normalize URI paths according to RFC 3986. Remove redundant and relative path components. Each path segment must be URI-encoded.

**Comment by matrinox** [comment]
@radar Solution comes from reading [this article](http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html). Specifically, this sentence in the 2nd point:

> Each path segment must be URI-encoded.

File: lib/aws_auth/utils.ex [hunk 1]
```diff
@@ -17,7 +17,13 @@ defmodule AWSAuth.Utils do
       do: "UNSIGNED-PAYLOAD",
       else: hashed_payload
 
-    "#{http_method}\n#{URI.encode(url) |> String.replace("$", "%24")}\n#{query_params}\n#{header_params}\n\n#{signed_header_params}\n#{hashed_payload}"
+    encoded_path =
+      path
```
Comment (radar) [inline lib/aws_auth/utils.ex:21]: This looks so much neater! Thank you.

**Review by radar — APPROVED** [review]

**Comment by radar** [comment]
I've just released 0.7.0 with this change included. I then released 0.7.1 because in the course of publishing 0.7.0 I saw a deprecation warning for `String.strip`. 

Feel free to use either version :)
